CREATE TABLE app_user (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR(200) NOT NULL UNIQUE, display_name VARCHAR(100) NOT NULL,
 password_hash VARCHAR(100) NOT NULL, feed_version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE category (id BIGINT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE);
INSERT INTO category VALUES (1,'Java'),(2,'Databases'),(3,'Distributed Systems'),(4,'AI'),(5,'Cloud'),(6,'Frontend'),(7,'Security'),(8,'Fintech'),(9,'DevOps'),(10,'Engineering');
CREATE TABLE subscription (
 user_id BIGINT REFERENCES app_user ON DELETE CASCADE,
 category_id BIGINT REFERENCES category, PRIMARY KEY(user_id,category_id)
);
CREATE INDEX subscription_category_idx ON subscription(category_id,user_id);
CREATE TABLE article (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK(id < 9007199254740991),
 author_id BIGINT NOT NULL REFERENCES app_user,
 title VARCHAR(200) NOT NULL, body TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE article_category (
 article_id BIGINT REFERENCES article ON DELETE CASCADE,
 category_id BIGINT REFERENCES category, PRIMARY KEY(article_id,category_id)
);
CREATE INDEX article_category_lookup ON article_category(category_id,article_id DESC);
CREATE TABLE feed_entry (
 user_id BIGINT REFERENCES app_user ON DELETE CASCADE,
 article_id BIGINT REFERENCES article ON DELETE CASCADE,
 PRIMARY KEY(user_id,article_id)
);
CREATE TABLE outbox (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 kind VARCHAR(20) NOT NULL CHECK(kind IN ('ARTICLE','USER')),
 aggregate_id BIGINT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), published_at TIMESTAMPTZ
);
CREATE INDEX outbox_pending ON outbox(id) WHERE published_at IS NULL;
-- Each durable per-user task is independently acknowledged and retryable.
CREATE TABLE processed_event (event_id BIGINT PRIMARY KEY, processed_at TIMESTAMPTZ NOT NULL DEFAULT now());
